# Generated by Django 5.1.1 on 2025-03-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='elimination_order',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
