# Generated by Django 5.1.1 on 2025-03-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_matchresult_elimination_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='elimination_order',
            field=models.JSONField(default=list),
        ),
    ]
