# Generated by Django 5.1.1 on 2025-05-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_matchresult_elimination_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='match_type',
            field=models.CharField(choices=[('ranked', 'Ranked'), ('unranked', 'Unranked')], default='ranked', max_length=20),
        ),
    ]
