# Generated by Django 5.1.1 on 2024-11-16 11:21

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_super_user'),
    ]

    def generate_users(apps, schema_editor):
        def generate_user(var_name, var_email, var_pass):
            from users.models import User
            if (var_name and var_email and var_pass):
                user: User = User.objects.create_user(
                    username=var_name,
                    first_name=var_name,
                    email=var_email,
                    password=var_pass,
                    is_verified=True)

                user.save()

        generate_user(
            os.environ.get('DJANGO_TEST_NAME_1'),
            os.environ.get('DJANGO_TEST_EMAIL_1'),
            os.environ.get('DJANGO_TEST_PASSWORD_1')
        )
        generate_user(
            os.environ.get('DJANGO_TEST_NAME_2'),
            os.environ.get('DJANGO_TEST_EMAIL_2'),
            os.environ.get('DJANGO_TEST_PASSWORD_2')
        )
        generate_user(
            os.environ.get('DJANGO_TEST_NAME_3'),
            os.environ.get('DJANGO_TEST_EMAIL_3'),
            os.environ.get('DJANGO_TEST_PASSWORD_3')
        )
        generate_user(
            os.environ.get('DJANGO_TEST_NAME_4'),
            os.environ.get('DJANGO_TEST_EMAIL_4'),
            os.environ.get('DJANGO_TEST_PASSWORD_4')
        )

    operations = [
        migrations.RunPython(generate_users),
    ]
