# Generated by Django 5.1.1 on 2025-02-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_test_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
