version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - websocket

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - backend

  ai_worker:
    build:
      context: ./ai
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data: